<a href="https://colab.research.google.com/github/mimiachiu/Deep-Learning-with-Python-Book/blob/master/Ch02_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [2]:
pip install keras

In [3]:
from keras.datasets import mnist #從keras匯入mnist手寫數字圖片資料集
(train_images, train_labels), (test_images, test_labels) = mnist.load_data() #載入資料並分成訓練和測試

Using TensorFlow backend.


11493376/11490434 [==============================] - 2s 0us/step


In [4]:
#訓練圖片共有60000張，測試圖片共有10000張，圖片是28x28大小的灰階圖，標籤是0~9的數字
print(train_images.shape)
print(train_labels.shape)
print(train_labels)
print(test_images.shape)
print(test_labels.shape)
print(test_labels)

(60000, 28, 28)
(60000,)
[5 0 4 ... 5 6 8]
(10000, 28, 28)
(10000,)
[7 2 1 ... 4 5 6]


In [5]:
from keras import models
from keras import layers

In [6]:
#建立兩個密集層(Dense layer)
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [7]:
#指定優化器、損失函數、評量準則
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

In [8]:
#對應建立的網路，需改變輸入形式，且數值需介於0~1
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [9]:
from keras.utils import to_categorical

In [10]:
#將標籤重新One-hot編碼
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [11]:
print(train_labels.shape)
print(train_labels)

(60000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [12]:
#開始訓練
network.fit(train_images, train_labels, epochs=5, batch_size=128)


Epoch 1/5
60000/60000 [==============================] - 4s 59us/step - loss: 0.2548 - accuracy: 0.9263
Epoch 2/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.1039 - accuracy: 0.9693
Epoch 3/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.0700 - accuracy: 0.9787
Epoch 4/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.0497 - accuracy: 0.9855
Epoch 5/5
60000/60000 [==============================] - 2s 32us/step - loss: 0.0375 - accuracy: 0.9885


In [13]:
#將測試圖片丟入訓練好的模型
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 71us/step
test_acc: 0.9797999858856201
